catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path(r'borrowed/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
]

djanbrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
import uuid 
import datetime
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

def current_year():
    return datetime.date.today().year

class Category(models.Model):
    name = models.CharField(max_length=200, help_text='Entrez une catégorie de livre')

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    year = models.IntegerField('Year', default=current_year, help_text='Année de publication')
    content = models.TextField(max_length=1000, help_text='Décrivez le livre')
    isbn = models.CharField('ISBN', max_length=13, unique=True, help_text='Maximum 13 caractères')
    category = models.ManyToManyField(Category, help_text='Choisissez une catégorie')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_category(self):
        return ', '.join([category.name for category in self.category.all()[:3]])

    display_category.short_description = 'Category'

class BookAvailability(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Identifiant unique à la librairie")
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        return bool(self.due_back and datetime.date.today() > self.due_back)

    LOAN_STATUS = (
        ('d', 'En attente'),
        ('o', 'En location'),
        ('a', 'Disponible'),
        ('r', 'Réservé'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='d',
        help_text='Disponibilité du livre')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Peut indiquer le livre comme rendu"),)

    def __str__(self):
        return '{0} ({1})'.format(self.id, self.book.title)


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    biography = models.TextField(max_length=1000, help_text='Décrivez une petit biographie')

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return '{0}, {1}'.format(self.last_name, self.first_name)

catalog/forms.py
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime

from django import forms


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
            help_text="Entrez une date jusqu'au mois prochain maximum.")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_("Date invalide - Date antérieur à aujourd'hui"))
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _("Date invalide - Vous ne pouvez pas aller au-delà du mois prochain"))
        return data

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from .models import Book, Author, BookAvailability, Category
from catalog.forms import RenewBookForm
import datetime

def index(request):
 
    num_books = Book.objects.all().count()
    num_availabilities = BookAvailability.objects.all().count()

    num_availabilities_open = BookAvailability.objects.filter(status__exact='a').count()

    num_authors = Author.objects.count()

    context = {
        'num_books': num_books,
        'num_availabilities': num_availabilities,
        'num_availabilities_open': num_availabilities_open,
        'num_authors': num_authors,
    }

    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookAvailability
    template_name = 'catalog/bookavailability_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookAvailability.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    model = BookAvailability
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookavailability_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        return BookAvailability.objects.filter(status__exact='o').order_by('due_back')

@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    book_availability = get_object_or_404(BookAvailability, pk=pk)

    if request.method == 'POST':

        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_availability.due_back = form.cleaned_data['renewal_date']
            book_availability.save()

            return HttpResponseRedirect(reverse('all-borrowed'))
            
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_availability': book_availability,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'biography']
    permission_required = 'catalog.can_mark_returned'


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'biography']
    permission_required = 'catalog.can_mark_returned'


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.can_mark_returned'


class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    fields = ['title', 'author', 'year', 'content', 'isbn', 'category']
    permission_required = 'catalog.can_mark_returned'


class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = ['title', 'author', 'year', 'content', 'isbn', 'category']
    permission_required = 'catalog.can_mark_returned'


class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    permission_required = 'catalog.can_mark_returned'

catalog/templates/catalog/author_confirm_delete.html
{% extends "layout.html" %}

{% block content %}

<h1>Supprimer cet auteur</h1>

<p>Êtes-vous sûr de vouloir supprimer : {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "layout.html" %}

{% block content %}

<h1>{{ author }} </h1>
<div>
    {{author.biography}}
</div>

{% if author.book_set.all %}
<div style="margin-left:20px;margin-top:20px">

  <h4>Livres de l'auteur</h4>

  <dl>
  {% for book in author.book_set.all %}
    <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookavailability_set.all.count}})</dt>
    <dd>{{book.content}}</dd>
  {% endfor %}
  </dl>

</div>
{% endif %}
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "layout.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "layout.html" %}

{% block content %}

<h1>Auteurs disponibles</h1>

{% if author_list %}
  <ul>

  {% for author in author_list %}
    <li>
      <a href="{{ author.get_absolute_url }}">
      {{ author }}
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>Aucun auteur disponible.</p>
{% endif %}
        
        
        
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "layout.html" %}

{% block content %}

<h1>Supprimer le livre de la bibliothèque</h1>

<p>Êtes-vous sûr de vouloir supprimer: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "layout.html" %}

{% block content %}
  <h1>Titre: {{ book.title }}</h1>

  <p><strong>Auteur:</strong> <a href="">{{ book.author }}</a></p>
  <p><strong>Synopsis:</strong> {{ book.content }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Catégories:</strong> {{ book.category.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Exemplaires</h4>

    {% for copy in book.bookavailability_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Date de retour:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Maison d'édition:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Identifiant:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "layout.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    
</form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "layout.html" %}

{% block content %}
  <h1>Livres</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Aucun livre disponible.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "layout.html" %}

{% block content %}
    <h1>Livre: {{book_availability.book.title}}</h1>
    <p>Emprunteur: {{book_availability.borrower}}</p>
    <p{% if book_availability.is_overdue %} class="text-danger"{% endif %}>Date de retour: {{book_availability.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

catalog/templates/catalog/bookavailability_list_borrowed_all.html
{% extends "layout.html" %}

{% block content %}
    <h1>Tous les livres empruntés</h1>

    {% if bookavailability_list %}
    <ul>

      {% for bookavailability in bookavailability_list %} 
      <li class="{% if bookavailability.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookavailability.book.pk %}">{{bookavailability.book.title}}</a> ({{ bookavailability.due_back }}) {% if user.is_staff %}- {{ bookavailability.borrower }}{% endif %} {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookavailability.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Aucun livre emprunté.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/bookavailability_list_borrowed_user.html
{% extends "layout.html" %}

{% block content %}
    <h1>Livres empruntés</h1>

    {% if bookavailability_list %}
    <ul>

      {% for bookavailability in bookavailability_list %}
      <li class="{% if bookavailability.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookavailability.book.pk %}">{{bookavailability.book.title}}</a> ({{ bookavailability.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Aucun livre emprunté.</p>
    {% endif %}
{% endblock %}